version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.12.0-stretch

commands:
  cache_yarn:
    parameters:
      cache_version:
        type: string
        default: v1
    steps:
      - restore_cache:
          keys:
          - npm-cache-{{ checksum "./yarn.lock" }}-<< parameters.cache_version >>-
          - npm-cache-{{ checksum "./yarn.lock" }}-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
          - ~/.cache/yarn
          key: npm-cache-{{ checksum "./yarn.lock" }}-<< parameters.cache_version >>-

jobs:
  build:
    executor: node
    steps:
      - checkout
      - cache_yarn
      - run: yarn build
      - run: yarn eslint src/js --ext .ts
  package:
    executor: node
    steps:
      - checkout
      - cache_yarn
      - run: yarn package
      - store_artifacts:
          path: extension.zip

workflows:
  version: 2
  on_commit:
    jobs:
      - build:
          filters:
            branches:
              ignore: /master/
